# Generated by Django 4.0.5 on 2022-06-04 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('JobSeekerapp', '0004_alter_works_from_alter_works_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='To',
            field=models.CharField(default=datetime.datetime(2022, 6, 4, 8, 37, 24, 938445, tzinfo=utc), max_length=12),
        ),
    ]
